### ISSUE TITLE
PRs

### ISSUE THREAD

**Issue by saksiva** [FAC-Sixteen/week-3-agony-yaunt#18]
I looked at your commits well done with the titles used. I can see that commits are uneven, so maybe try and keep it in mind for the next project.

**Comment by RohanSSS** [comment]
![commit-stats](https://user-images.githubusercontent.com/20860431/54818284-c7a52000-4c90-11e9-870e-18f0d0f71764.png)

Very uneven commits. Sam has more than everyone else combined
